version: "3"

services:
  mysql:
    image: mysql
    env_file: backend/.env
    volumes:
        - ./database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "liteThinking"
      MYSQL_USER: "liteThinking"
      MYSQL_PASSWORD: "liteThinking"
      MYSQL_DATABASE: "liteThinking_db"

